FROM windowsservercore
LABEL Description="IIS" Vendor="Microsoft" Version="10.0.10586"
ADD HybridInstaller.ps1 /Windows/Temp/HybridInstaller.ps1
RUN powershell -executionpolicy bypass C:\Windows\Temp\HybridInstaller.ps1 -RunNative
