# This dockerfile utilizes components licensed by their respective owners/authors.
# Prior to utilizing this file or resulting images please review the respective licenses at: https://golang.org/LICENSE

FROM windowsservercore

MAINTAINER neil.peterson@microsoft.com

LABEL Description="GO Programming Language" Vendor="Google" Version="1.5.1"

RUN powershell -Command \
	Invoke-WebRequest -Method Get -Uri https://storage.googleapis.com/golang/go1.6.windows-amd64.msi -OutFile c:\go1.6.windows-amd64.msi ; \
	start-Process c:\go1.6.windows-amd64.msi -ArgumentList '/qn' -Wait ; \
	Remove-Item c:\go1.6.windows-amd64.msi -Force

WORKDIR /go/bin

CMD ["go.exe version"]